<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="Service" targetNamespace="http://www.example.org/Service/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/Service/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="Service_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="ServiceSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://www.example.org/Service/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="Service_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="testOperationRequest">
    <wsdl:part element="tns:testOperation" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="testOperationResponse">
    <wsdl:part element="tns:testOperationResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Service">
    <wsdl:operation name="testOperation">
      <wsdl:input message="tns:testOperationRequest"/>
      <wsdl:output message="tns:testOperationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServiceSOAP" type="tns:Service">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="testOperation">
      <soap:operation soapAction="http://www.example.org/Service/testOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Service">
    <wsdl:port binding="tns:ServiceSOAP" name="ServiceSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>